# This File should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts " ==================== INICIANDO O SEEDS EM #{Time.now} ======================"
categories = [{id: 1, name: 'Hidratantes'}, {id: 2, name: 'ESCOVA PROGRESSIVA'}, {id: 3, name: 'CONDICIONADOR'}, {id: 4, name: 'SHAMPOO'}]

categories.each do |category|
  puts Category.create(category)
end

sku = [('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten

products = [
  {name: ' Kit Rapunze 230ml' , description: ' O Combo Rapunzel contém: 1- Shampoo Rejuvenescedor Lola Rapunzel 230ml 1- Tônico do Crescimento Lola Rapunzel 230ml 1- Milk Spray Lola Rapunzel 230ml INDICAÇÃO DE FREQUÊNCIA DE USO Para perda de cabelo severa: aplique diariamente. Para perda de cabelo moderada: aplique três vezes por semana. Para um tratamento preventivo e pontual: aplique duas vezes por semana. Após o período de tratamento (três meses), continue aplicando duas vezes por semana para manutenção. ' , description_short: ' Kit Rapunze (Shampoo, Tônico do Crescimento e Milk Spray) 230ml cada ', sku: ' ESC2JWJE1 ' ,image1: File.open("#{Rails.root}/public/images/AlvaBatom 10g.jpg"), image2: nil},

{name: ' Morte Súbita Hidratante 450g ' , description: ' Os produtos da Lola Cosmetics são os queridinhos entre as mulheres. Não é à toa que a marca é hoje uma das maiores e mais populares desenvolvedoras de cremes, hidratantes e outros itens para cabelos, pois os produtos são compostos com ingredientes naturais para garantir a máxima saúde dos fios, como o óleo de argan, o óleo de macadâmia e outros. Esses produtos têm feito a felicidade das mulheres, conferindo cabelos mais hidratados, macios e bonitos. Confira! ' , description_short: ' Morte Súbita Máscara Super Hidratante 450g ', sku: ' ESC2JWJE2 ' ,image1: File.open("#{Rails.root}/public/images/Morte Súbita.jpg"), image2: File.open("#{Rails.root}/public/images/morte subita hidratação2.jpg")},



{name: ' Creme Monange 80g ' , description: ' Hidratante para as mãos. Desenvolvido especialmente para o cuidado das mãos, Possui fórmula de rápida absorção, enriquecida com Manteiga de Cupuaçu e Vitamina F.Embalagem em bisnaga de 80 gramas ' , description_short: ' Creme Hidrantante para Mãos Monange 80g ', sku: ' ESC2JWJE3 ' ,image1: File.open("#{Rails.root}/public/images/Creme Hidrantante para Mãos Monange.jpg"), image2: File.open("#{Rails.root}/public/images/Monange Hidratante para Mãos 2.jpg")},


{name: ' Creme Bio C Firmador ' , description: ' O Creme Firmador Corporal devolve a elasticidade e a firmeza à pele, perdidas pela ação do tempo e das agressões ambientais. Seus ativos: Colágeno, Elastina e Extrato de Shitake possuem função de manter a firmeza da pele, impedindo a sua flacidez. Sua composição de fácil absorção, possui ação tensora e hidratante, a qual melhora a textura, mantendo a tonicidade da pele. ' , description_short: ' Creme Bio C Corporal Firmador ', sku: ' ESC2JWJE4 ' ,image1: File.open("#{Rails.root}/public/images/Creme Bio C Corporal Firmador.jpg"), image2: nil},


{name: ' Lux Refil Brisa de Lavanda ' , description: ' Com o novo Lux Brisa de Lavanda, dê aos seus sentidos uma experiência agradável e refrescante com uma fragrância delicada composta com notas de Lavanda e Bergamota. ' , description_short: ' Sabonete Líquido Lux Refil Brisa de Lavanda ', sku: ' ESC2JWJE5 ' ,image1: File.open("#{Rails.root}/public/images/Sabonete Líquido Lux Refil Brisa de Lavanda.jpg"), image2: nil},

{name: ' Lux Refil Brisa Floral ' , description: ' Com o novo Lux Brisa Floral,sinta-se delicadamente perfumada e instantaneamente renovada! Formulado com uma fragrância fresca restauradora de Verbena e Chá Verde. ' , description_short: ' Sabonete Líquido Lux Refil Brisa Floral ', sku: ' ESC2JWJE6 ' ,image1: File.open("#{Rails.root}/public/images/Sabonete Líquido Lux Refil Brisa Floral.jpg"), image2: nil},
{name: ' Lux Refil Magical Spell ' , description: ' Um Sabonete Líquido finamento perfumado com Essência de Orquídea Negra e Óleo de Zimbro. Essa combinação é inspirada em flores exóticas e pérolas de fragrância que te dão um perfume cativante que dura por até 8 horas na pele após o banho. ' , description_short: ' Sabonete Líquido Lux Refil Magical Spell ', sku: ' ESC2JWJE7 ' ,image1: File.open("#{Rails.root}/public/images/Sabonete Líquido Lux Refil Magical Spell.jpg"), image2: nil},
{name: ' Lux Fresh Passion ' , description: ' Com Lux Íntimo Fresh Passion, descubra a sensação e prazer de estar fresca e perfumada, além de pronta e confiante para fazer acontecer o que quiser, mesmo com a correria do dia-a-dia. Com uma fórmula especialmente desenvolvida para respeitar o pH da área íntima, este sabonete ultra feminino possui um perfume único e refrescante das flores de Lótus e Verbena, deixando você cuidada e delicadamente perfumada. ' , description_short: ' Sabonete Líquido Íntimo Lux Fresh Passion ', sku: ' ESC2JWJE8 ' ,image1: File.open("#{Rails.root}/public/images/Sabonete Líquido Íntimo Lux Fresh Passion.jpg"), image2: nil},
{name: ' Protetor Solar Neutrogena FPS 50 ' , description: ' NEUTROGENA® Sun Fresh FPS 50 possui fórmula não oleosa e com alto poder de absorção, deixando a pele do rosto e do corpo protegida, hidratada e sequinha. ' , description_short: ' Protetor Solar Neutrogena Sun Fresh 120ml FPS 50 ', sku: ' ESC2JWJE9 ' ,image1: File.open("#{Rails.root}/public/images/Protetor Solar Neutrogena Sun Fresh 120ml FPS 50.jpg"), image2: File.open("#{Rails.root}/public/images/Protetor Solar Neutrogena FPS 502.jpg")},
{name: ' Hair Spray Cless 400ml ' , description: ' O Hair Spray Charming Extra Forte fixa e modela os cabelos de maneira natural, finalizando os penteados e permitindo criar os mais diversos estilos. ' , description_short: ' Hair Spray Cless Charming Black Extra Forte 400ml ', sku: ' ESC2JWJE10 ' ,image1: File.open("#{Rails.root}/public/images/Hair Spray Cless Charming Black Extra Forte 400ml.jpg"), image2: nil},
{name: ' Pomada Charming 50G ' , description: ' A Pomada EXTRAFORTE EFEITO SECO Charming é ideal para modelar, estilizar e fixar os fios, controlando o volume. ' , description_short: ' Pomada Charming Modeladora Efeito Seco 50G ', sku: ' ESC2JWJE11 ' ,image1: File.open("#{Rails.root}/public/images/Pomada Charming Modeladora Efeito Seco 50G.png"), image2: nil},
{name: ' Lenço de Limpeza Loreal ' , description: ' O Lenço Micelar Loréal Paris foi especialmente desenvolvida para limpar a pele. Com o alto poder de limpeza e purificação, sua fórmula capta e elimina as impurezas e maquiagem, revelando uma pele perfeitamente limpa, reequilibrada e suave sem agredi-la. ' , description_short: ' Lenço de Limpeza Loreal 5 em 1 Micelar c/25un. ', sku: ' ESC2JWJE12 ' ,image1: File.open("#{Rails.root}/public/images/Lenço de Limpeza Loreal 5 em 1 Micelar c 25un.jpg"), image2: nil},
{name: ' Solução de Limpeza Loreal ' , description: ' A nova Água Micelar de LOréal Paris foi especialmente desenvolvida para limpar a pele. Com o alto poder de limpeza e purificação, sua fórmula capta e elimina as impurezas e maquiagem, revelando uma pele perfeitamente limpa, reequilibrada e suave sem agredi-la. ' , description_short: ' Demaquilante Solução de Limpeza Loreal 5 em 1 Água Micelar 200ml ', sku: ' ESC2JWJE13 ' ,image1: File.open("#{Rails.root}/public/images/Demaquilante Solução de Limpeza Loreal 5 em 1 Água Micelar 200ml.jpg"), image2: nil},
{name: ' Condicionador Seduction 450ml ' , description: ' Ativos hidratantes, para cabelos ressecados e danificados. Hidratação intensa, resistência e maleabilidade aos fios. ' , description_short: ' Condicionador Seduction Hidratação Intensa 450ml ', sku: ' ESC2JWJE14 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Seduction Hidratação Intensa 450ml.jpg"), image2: nil},
{name: ' Condicionador Seduction Pós Progressiva ' , description: ' Hidrata, prolonga e intensifica o efeito liso. ' , description_short: ' Condicionador Seduction Pós Progressiva 450ml ', sku: ' ESC2JWJE15 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Seduction Pós Progressiva 450ml.jpg"), image2: nil},
{name: ' Condicionador Seduction Pós Coloração ' , description: ' Para manter e prolongar a cor dos cabelos coloridos. Controla e proporciona maciez e brilho ' , description_short: ' Condicionador Seduction Pós Coloração 450ml ', sku: ' ESC2JWJE16 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Seduction Pós Coloração 450ml.jpg"), image2: nil},
{name: ' Condicionador Seduction Cachos 450ml ' , description: ' Para deixar os cachos definidos, naturais e concentrados. Deixa os fios maleáveis, formando um filme protetor para reter a umidade natural, eliminando o frizz. ' , description_short: ' Condicionador Seduction Cachos Definidos 450ml ', sku: ' ESC2JWJE17 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Seduction Cachos Definidos 450ml.jpg"), image2: nil},
{name: ' Condicionador Seduction Desamarelador ' , description: ' Neutraliza o amarelado dos cabelos loiros, grisalhos ou com mechas, devolve a vitalidade dos cabelos e proporciona brilho intenso ' , description_short: ' Condicionador Seduction Desamarelador 450ml ', sku: ' ESC2JWJE18 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Seduction Desamarelador 450ml.jpg"), image2: nil},
{name: ' Kit Seduction Mandioca 1000ml ' , description: ' Kit Seduction 10X1 Força foi desenvolvido para fortalecer todos os tipos de cabelos e estimular o crescimento ' , description_short: ' Kit Seduction 10X1 Força Shampoo + Condicionador Mandioca 1000ml ', sku: ' ESC2JWJE19 ' ,image1: File.open("#{Rails.root}/public/images/Kit Seduction 10X1 Força Shampoo + Condicionador Mandioca 1000ml.jpg"), image2: nil},
{name: ' Condicionador Elseve Óleo ' , description: ' Um cabelo seco parece estar sem vida, pois ele está opaco, sem brilho e tem um toque áspero. Isso faz com que ele perca a sua beleza. A maioria dos produtos ou pesam demais ou não são suficientemente nutritivos. O segredo dos óleos de flores preciosas para uma nutrição perfeita & uma leveza infinita estão no shampoo Elseve Óleo Extraordinário Nutrição Intensa. Resultado: Os cabelos secos ficam cheios de vida. Sublimes em todos os ângulos. Textura ultracremosa e rica. ' , description_short: ' Condicionador Elseve Óleo Extraordinário Nutrição Intensa ', sku: ' ESC2JWJE20 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Elseve Óleo Extraordinário Nutrição Intensa.jpg"), image2: nil},
{name: ' Creme Elseve Supreme ' , description: ' Volume excessivo, fios rebeldes, frizz e efeito armado? Tem dias em que os cabelos parecem ter vida própria e não há uma única solução para controlá-los. E se um produto fosse capaz de agir ao mesmo tempo nessas 4 dimensões do problema? ' , description_short: ' Creme de Tratamento Elseve Supreme Control 4D ', sku: ' ESC2JWJE21 ' ,image1: File.open("#{Rails.root}/public/images/Creme de Tratamento Elseve Supreme Control 4D.jpg"), image2: nil},
{name: ' Creme Elseve Resist  ' , description: ' O cabelo Fino muito fragilizado está com falta de nutrientes essenciais. Ele perde consistência no comprimento e por isso quebra e cai com facilidade. E se a ciência pudesse fortalecer os seus cabelos devolvendo o que foi perdido? Os laboratórios Loréal unem Arginina com micro-proteína em uma poderosa fórmula que reforça os cabelos finos desde a raiz, encorpa os fios na medida certa e favorece uma restituição de massa no comprimento dos fios. Alinha de produtos Arginina Resist X3 Restituição de Massa oferece uma tripla ação. Encorpa e reforça a fibra, nutre o bulbo capilar, e o cabelo cresce mais forte e consistente. ' , description_short: ' Creme de Tratamento Elseve Resist X3 Restituição de Massa ', sku: ' ESC2JWJE22 ' ,image1: File.open("#{Rails.root}/public/images/Creme de Tratamento Elseve Resist X3 Restituição de Massa.jpg"), image2: nil},
{name: ' Shampoo Elseve Quera Liso ' , description: ' Inovação micro-queratina (MQ). Liso Solto perfeito fio a fio. Corrige as mínimas irregularidades do fio sem pesar. Ideal para cabelos lisos com escova. ' , description_short: ' Shampoo Elseve Quera Liso Microqueratina Lisos com Escova 400ml ', sku: ' ESC2JWJE23 ' ,image1: File.open("#{Rails.root}/public/images/Shampoo Elseve Quera Liso Microqueratina Lisos com Escova 400ml.jpg"), image2: nil},
{name: ' Condicionador Elseve Quera Liso ' , description: ' Inovação micro-queratina (MQ). Liso Solto perfeito fio a fio. Corrige as mínimas irregularidades do fio sem pesar. Ideal para cabelos lisos com escova. ' , description_short: ' Condicionador Elseve Quera Liso Microqueratina Lisos com Escova 400ml ', sku: ' ESC2JWJE24 ' ,image1: File.open("#{Rails.root}/public/images/Condicionador Elseve Quera Liso Microqueratina Lisos com Escova 400ml.jpg"), image2:  File.open("#{Rails.root}/public/images/Condicionador Elseve Quera Liso2.jpg")},
{name: ' Creme Elseve Arginina ' , description: ' Seus cabelos fragilizados têm tendência à queda? Você está à procura de um tratamento para queda de cabelo? Seus cabelos se fixam menos na raiz, têm resistência mais baixa às agressões externas e acabam caindo? A linha Fortificante Elseve Arginina Resist X3 os deixa fortes e mais resistentes. ' , description_short: ' Creme de Tratamento Elseve Arginina ', sku: ' ESC2JWJE25 ' ,image1: File.open("#{Rails.root}/public/images/Creme de Tratamento Elseve Arginina.jpg"), image2: nil},
{name: ' 1Ka Escova Inteligente ' , description: ' A Escova Inteligente 1Ka é compatível com todos os tipos de química e todos os tipos de cabelos. Ela permite que os cabelos sejam lavados no mesmo dia. A Escova Inteligente (Protetor Térmico) 1Ka é indicada para reduzir o volume, hidratar e dar brilho aos fios. Indicações de Uso: Cabelos ondulados, crespos, volumosos e ressecados. Diferencial do produto: Reconstrução capilar + proteção térmica em um único produto ' , description_short: ' 1Ka Escova Inteligente Protetor Térmico - Passo 2 - 1Litro ', sku: ' ESC2JWJE26 ' ,image1: File.open("#{Rails.root}/public/images/1Ka Escova Inteligente Protetor Térmico - Passo 2 - 1Litro.jpg"), image2: nil},
{name: ' Madame Lis Délicat ' , description: ' O Btx Mask Control da Madame Lis é uma Máscara Intensiva que contém polifenóis e ácidos graxos, devolvendo sedosidade e umidade aos cabelos. Com o efeito de reduzir o volume, o Btx Mask Control Madame Lis trata os cabelos danificados logo na sua primeira aplicação.O Btx Mask Control da Madame Lis é enriquecido com óleos naturais que repara a fibra capilar e promove a selagem da cutícula, amaciando e restaurando a flexibilidade natural dos fios, promovendo o realinhamento e selamento capilar. Especialmente formulado para cabelos volumosos e indisciplinados, o Btx Mask Control da Madame Lis promove o controle de instabilidade do pH. ' , description_short: ' Madame Lis Délicat Série Btx Mask Control 1Kg ', sku: ' ESC2JWJE27 ' ,image1: File.open("#{Rails.root}/public/images/Madame Lis Délicat Série Btx Mask Control 1Kg.jpg"), image2: nil},
{name: ' Portier Fine ' , description: ' Escova Portier é um realinhamento térmico, da Fine Cosméticos, que trata através da reconstrução por Proteínas, Queratina, Arginina, Vitaminas A, D, E, F, Gérmen de Trigo, Favo de Mel e Aloe Vera, que são absorvidos e depois retidos dentro dos fios pelo processo de selamento térmico realizado apenas pela prancha. ' , description_short: ' Portier Fine Escova Progressiva 2x1000ml ', sku: ' ESC2JWJE28 ' ,image1: File.open("#{Rails.root}/public/images/Portier Fine Escova Progressiva 2x1000ml.jpg"), image2: nil},
{name: ' Lanza Healing Nourish Shampoo ' , description: ' A Linha Healing Nourish utiliza o exclusivo Sistema Anágena 7 que mantém o cabelo na fase anágena (crescimento) já visando as setes áreas para nutrir o crescimento do cabelo saudável. O Shampoo Estimulante Healing Nourish Lanza, especialmente formulado para cabelos finos. Remove o excesso de oleosidade e resíduos. Reduz a queda dos fios. Formulado com Keratin Healing System e protetores da cor. Gentilmente remove o excesso de sebo e resíduo para promover o cabelo com aparência mais completa. Fórmula livre de cloreto e livre de sulfato de sódio e é cor-seguro e suave o suficiente para usar todos os dias. ' , description_short: ' Lanza Healing Nourish Shampoo Estimulante 300ml ', sku: ' ESC2JWJE29 ' ,image1: File.open("#{Rails.root}/public/images/Lanza Healing Nourish Shampoo Estimulante 300ml.jpg"), image2: nil},
{name: ' Remedy Cleanser Shampoo 300ml ' , description: ' O Shampoo Cleanser Remedy Healing Lanza possui uma fórmula calmante que restaura a saúde dos cabelos e couro cabeludo. Contém Shino Mint e extrato de Papaia para equilibrar a oleosidade do couro cabeludo e agua de coco para acalmar e nutrir. O Keratin Healing System repõe a proteína da queratina vital para cabelos fortes e brilhantes. Livre de Sulfato, Cloreto de Sódio e Parabeno. Protege a cor. ' , description_short: ' Lanza Healing Remedy Cleanser Shampoo 300ml ', sku: ' ESC2JWJE30 ' ,image1: File.open("#{Rails.root}/public/images/Lanza Healing Remedy Cleanser Shampoo 300ml.jpg"), image2: nil},
{name: ' Smooth Shampoo 300ml ' , description: ' O Shampoo Cleanser Remedy Healing Lanza possui uma fórmula calmante que restaura a saúde dos cabelos e couro cabeludo. Contém Shino Mint e extrato de Papaia para equilibrar a oleosidade do couro cabeludo e agua de coco para acalmar e nutrir. O Keratin Healing System repõe a proteína da queratina vital para cabelos fortes e brilhantes. Livre de Sulfato, Cloreto de Sódio e Parabeno. Protege a cor. ' , description_short: ' Lanza Healing Smooth Shampoo 300ml ', sku: ' ESC2JWJE31 ' ,image1: File.open("#{Rails.root}/public/images/Lanza Healing Smooth Shampoo 300ml.jpg"), image2: nil},
{name: ' G.Hair Marroquina ' , description: ' Tratamento Capilar Marroquino G.hair - Encontra-se além da queratina e argila branca, extrato de cacau que trata os cabelos danificados e crespos de maneira eficaz e duradoura. ' , description_short: ' G.Hair Escova Progressiva Marroquina Passo 2 - 1000ml (Inoar) ', sku: ' ESC2JWJE32 ' ,image1: File.open("#{Rails.root}/public/images/G.Hair Escova Progressiva Marroquina Passo 2 - 1000ml (Inoar).jpg"), image2: nil},
{name: ' K.Pro Caviar Condicionador ' , description: ' Caviar, a mais avançada linha para tratamento e proteção diária dos cabelos. Com os benefícios inovadores do Extrato de Caviar e organosilicones para potencializar a fixação dos pigmentos e proteger a sedosidade. Caviar Condicionador Leave-in contribui para deixar os cabelos macios e protegendo contra os danos da escova e da chapinha. Proteção térmica total. ' , description_short: ' K.Pro Caviar Condicionador leave-in spray 200ml ', sku: ' ESC2JWJE33 ' ,image1: File.open("#{Rails.root}/public/images/K.Pro Caviar Condicionador leave-in spray 200ml.jpg"), image2: nil},
{name: ' Cadiveu Plástica ' , description: ' A Selagem Térmica Plática dos Fios CADIVEU é um reestruturante termoativada. Indicada para todos os tipos de cabelo, torna os fios lisos, brilhantes e sem frizz por 3 meses. ATIVOS PRINCIPAIS - Argina, Açai e pH Ácido (Ácido Acético). O ph ácido da Selagem térmica sobre os cabelos, quando em contato com o calor da prancha , torna os cabelos lisos. Os ativos açai e arginina, presentes na fórmula se fixam na parte externa dos fios. Essa ação realinha as cutículas do cabelo, proporcionando brilho extremo. O resultado da Selagem Térmica deve-se à ação do pH Ácido sobre as cutículas do cabelo. ' , description_short: ' Cadiveu Plástica dos Fios Kit Selagem Térmica - 3 Produtos ', sku: ' ESC2JWJE34 ' ,image1: File.open("#{Rails.root}/public/images/Cadiveu Plástica dos Fios Kit Selagem Térmica - 3 Produtos.jpg"), image2: nil},
{name: ' Maria Escandalosa Máscara ' , description: ' Os agentes emolientes do Beautox White Máscara Escandalosa são ativados através de agentes Térmicos (como por exemplo, secador e prancha.) A redução de volume, eliminação do frizz, resistência e brilho dos fios é algo que faz o Beautox White ser um produto de incrível qualidade, sendo um dos mais procurados por profissionais. Sua função é desenvolver a massa capilar perdida pela ação do sol, chapinha, secador, processos químicos e outros componentes internos e externos. ' , description_short: ' Maria Escandalosa Máscara Beautox White 1Kg ', sku: ' ESC2JWJE35 ' ,image1: File.open("#{Rails.root}/public/images/Maria Escandalosa Máscara Beautox White 1Kg.jpg"), image2: nil},
{name: ' Felps XBTX Capilar em Massa Óleo de Argan e Macadâmia 1kg ' , description: ' Felps XBTX Capilar em Massa é um tratamento eficaz tanto quanto uma Escova Progressiva, um tratamento moderno a base de Oleo de Argan e Macadâmia, super pratico na Redução de Volume e Alisamento Capilar, trata toda a estrutura da fibra, mantendo os fios alinhados, nutridos, fortes, saudáveis e sem frizz. Com sua exclusiva fórmula a base de Argan e Macadâmia o XBTX Capilar Felps age no selamento das cutículas e reposição de massa, recuperando toda a estrutura capilar. ' , description_short: ' Felps XBTX Capilar em Massa Óleo de Argan e Macadâmia 1kg ', sku: ' ESC2JWJE36 ' ,image1: File.open("#{Rails.root}/public/images/Felps XBTX Capilar em Massa Óleo de Argan e Macadâmia 1kg.jpg"), image2: nil},
{name: ' Felps Profissional Escova Progressiva XBTX de Okra 2x1000ml ' , description: ' Após minuciosas pesquisas, apresentamos o que há de mais inovador em ativos para tratamento, redução de volume e alisamento. Desenvolve a resistência e a força da fibra capilar. O extrato de Okra é um ativo que adere à superfície dos cabelos promovendo o selamento das cutículas e reposição de massa, recuperando a estrutura capilar. Contem Óleo de Argan. Cabelo liso de 95% a 100% na primeira aplicação. Cabelos Hidratados. Desenvolve a resistência e a força da fibra capilar. ' , description_short: ' Felps Profissional Escova Progressiva XBTX de Okra 2x1000ml ', sku: ' ESC2JWJE37 ' ,image1: File.open("#{Rails.root}/public/images/Felps Profissional Escova Progressiva XBTX de Okra 2x1000ml.jpg"), image2: nil},
{name: ' Zap All Time Escova Progressiva Redutora 2x1000ml ' , description: ' A Escova Progressiva Redutora Zap All Time possui uma fórmula elaborada a partir de ingredientes naturais, devolvendo aos fios os nutrientes que asseguram nutrição e resistência, proporcionando cabelos com um liso perfeito, natural, brilhante e sem frizz. Os princípios ativos da Escova Progressiva Zap All Time selam as cutículas e repõem a massa dos fios. O resultado são maravilhosos! A Zap Escova Progressiva All Time deixa os cabelos restaurados e profundamente hidratados. Zap All Time é compatível com todos os cabelos e com outros processos químicos, além de permitir que os fios sejam lavados logo depois do procedimento. ' , description_short: ' Zap All Time Escova Progressiva Redutora 2x1000ml ', sku: ' ESC2JWJE38 ' ,image1: File.open("#{Rails.root}/public/images/Zap All Time Escova Progressiva Redutora 2x1000ml.jpg"), image2: nil},
{name: ' G.Hair Escova Progressiva ZUP! Help Progress 2x1000ml ' , description: ' G.Hair Zup Help Progress é uma escova progressiva redutora de volume elaborada para alisar de forma adequada e eficiente os cabelos. Sua indicação é para todos os tipos de cabelos. O Shampoo Zup Help Progress foi desenvolvido especialmente para tratar e limpar os cabelos, com pH equilibrado e óleo de germem de trigo, limpa removendo as impurezas dos fios, preparando-os para receber os ativos redutores de tratamento. O Tratamento Anti-Volume ZUP é indicado para todos os tipos de cabelos, possui potente ação redutora de volume além de contribuir na reposição de queratina, proporcionando um cabelo liso de aspecto natural, com brilho e maciez. ' , description_short: ' G.Hair Escova Progressiva ZUP! Help Progress 2x1000ml ', sku: ' ESC2JWJE39 ' ,image1: File.open("#{Rails.root}/public/images/G.Hair Escova Progressiva ZUP! Help Progress 2x1000ml.jpg"), image2: nil},
{name: ' Shampoo TRESemmé Perfeitamente (Des)Arrumado - 400g ' , description: ' O Shampoo TRESemmé® Perfeitamente (Des)arrumado foi especialmente desenvolvido para mulheres que desejam o look ondulado. Com extratos de algas marinhas e sem silicone, prepara o cabelo para os próximos passos da linha Perfeitamente (Des)arrumado. ' , description_short: ' Shampoo TRESemmé Perfeitamente (Des)Arrumado - 400g ', sku: ' ESC2JWJE40 ' ,image1: File.open("#{Rails.root}/public/images/Shampoo TRESemmé Perfeitamente (Des)Arrumado - 400g.jpg"), image2: nil},
{name: ' BioartMáscara de Argila Peeling de Cristais 30mL ' , description: ' Excelente para esfoliar sem agredir a pele do rosto, pescoço e colo. Indicado para todos os tipos de pele. Ideal para peles sensíveis, pois não causa alergias. ' , description_short: ' BioartMáscara de Argila Peeling de Cristais 30mL ', sku: ' ESC2JWJE41 ' ,image1: File.open("#{Rails.root}/public/images/BioartMáscara de Argila Peeling de Cristais 30mL.jpg"), image2: nil},
{name: ' AlvaDuo de Sombra 10g ' , description: ' Proporciona um olhar marcante e uma cobertura perfeita da cor por horas, sem borrar ou escorrer. Tem uma fórmula inovadora com pó micronizado, deixando uma textura ultrafina que cobre homogeneamente a pele sem desbotar. ' , description_short: ' AlvaDuo de Sombra 10g ', sku: ' ESC2JWJE42 ' ,image1: File.open("#{Rails.root}/public/images/AlvaDuo de Sombra 10g.jpg"), image2: nil},
{name: ' VyvedasCondicionador Maracujá da Amazônia ' , description: ' Condiciona, nutre e hidrata os fios dos cabelos, deixando-os mais leves, macios e sedosos.Produzido através do óleo vegetal de Maracujá e da manteiga de Cupuaçu, romove o desembaraço, amaciando os fios.Libera sílica, que atua protegendo os fios dos efeitos externos. Tem aroma suave e é indicado para ambos os sexos. ' , description_short: ' VyvedasCondicionador Maracujá da Amazônia ', sku: ' ESC2JWJE43 ' ,image1: File.open("#{Rails.root}/public/images/VyvedasCondicionador Maracujá da Amazônia.jpg"), image2: nil},
{name: ' Surya Hidratante Facial com Cacau Amazônia Preciosa 80g ' , description: ' Hidratante e nutritivo, para todos os tipos de pele. Tem sua essência retirada da casca da árvore Preciosa, encontrada na Amazônia. Sua fórmula é rica em cacau e contém exóticos óleos vegetais. ' , description_short: ' Surya Hidratante Facial com Cacau Amazônia Preciosa 80g ', sku: ' ESC2JWJE44 ' ,image1: File.open("#{Rails.root}/public/images/SuryaHidratante Facial com Cacau Amazônia Preciosa 80g.jpg"), image2: nil},
{name: ' VyvedasGeléia Esfoliante Litsea Cubeba 260g ' , description: ' É indicado para peles sensíveis, inclusive para alérgicos. Geleia esfoliante concentrada, que proporciona a renovação celular, hidratando a pele e deixando uma sensação de refrescância e limpeza. Produzida com semente de Nozes e Amêndoas e óleos de Litsea e Castanha do Pará esfolia a pele com suavidade e eficácia. Não contém abrasivos e ajuda a combater o envelhecimento e radicais livres através das propriedades antioxidantes. Ajuda a preparar a pele para a hidratação e para o auto bronzeamento. Tem aroma refrescante e bactericida. ' , description_short: ' VyvedasGeléia Esfoliante Litsea Cubeba 260g ', sku: ' ESC2JWJE45 ' ,image1: File.open("#{Rails.root}/public/images/VyvedasGeléia Esfoliante Litsea Cubeba 260g.jpg"), image2: nil},
{name: ' Arte dos AromasSabonete Esfoliante Buriti 250mL ' , description: ' Sabonete esfoliante para o rosto e corpo. Esfolia de forma suave e eficaz, proporcionado uma pele macia, limpa e sedosa. Promove vitalidade, renovação celular e suavidade. Além de ser um potente hidratante rico em vitamina A, possui propriedades antienvelhecimento, aumentando a elasticidade da pele.Seu ingrediente ativo em destaque, o Buriti, possui propriedades emolientes, que proporcionam maciez e um toque sedoso à pele. Revitaliza peles cansadas, nutrindo-as com sua quantidade significativa de provitamina A e seu efeito cicatrizante. ' , description_short: ' Arte dos AromasSabonete Esfoliante Buriti 250mL ', sku: ' ESC2JWJE46 ' ,image1: File.open("#{Rails.root}/public/images/Arte dos AromasSabonete Esfoliante Buriti 250mL.jpg"), image2: nil},
{name: ' Arte dos AromasSais de Banho Lavanda - Lemongrass - Menta - Alecrim 252g ' , description: ' Contém 14 unidades de 18g cada. Tem efeito efervescente e espumante. Indicado para proporcionar um banho relaxante e perfumado, trazendo harmonia, equilíbrio e bem estar. Possui propriedades que tonificam e refrescam a pele. ' , description_short: ' Arte dos AromasSais de Banho Lavanda - Lemongrass - Menta - Alecrim 252g ', sku: ' ESC2JWJE47 ' ,image1: File.open("#{Rails.root}/public/images/Arte dos AromasSais de Banho Lavanda - Lemongrass - Menta - Alecrim 252g.jpg"), image2: nil},
{name: ' Arte dos AromasShampoo Andiroba 250mL ' , description: ' É indicado para cabelos quebradiços, frágeis e oleosos.Lava, regenerando o couro cabeludo e os fios, proporcionando a hidratação do cabelo.Deixa os cabelos com maior luminosidade e brilho.Produzido a partir do fruto da Andiroba, de onde é extraído um óleo que tem propriedades que suavizantes e emolientes, propicia maior maciez aos cabelos.Não testado em animais.Não contém sal, corantes e parabenos. ' , description_short: ' Arte dos AromasShampoo Andiroba 250mL ', sku: ' ESC2JWJE48 ' ,image1: File.open("#{Rails.root}/public/images/Arte dos AromasShampoo Andiroba 250mL.jpg"), image2: nil},
{name: ' SouvieÓleo Vegetal Corporal Orgânico Gestante 90mL ' , description: ' Hidrata profundamente e auxilia melhorando a elasticidade, firmando a pele e prevenindo estrias.Foi cuidadosamente elaborado para reestruturar o equilíbrio lipídico e prevenir o ressecamento da pele da gestante.Contém óleos orgânicos de girassol, coco, rosa mosqueta e castanha-do-pará, ricos em vitaminas A, B, C e E, responsáveis pela perfeita nutrição da pele, reforçando sua função protetora natural e garantindo uma pele saudável. ' , description_short: ' SouvieÓleo Vegetal Corporal Orgânico Gestante 90mL ', sku: ' ESC2JWJE49 ' ,image1: File.open("#{Rails.root}/public/images/SouvieÓleo Vegetal Corporal Orgânico Gestante 90mL.jpg"), image2: nil},
{name: ' BioartMáscara de Argila Rosa 30mL ' , description: ' Excelente para regenerar e hidratar a pele do rosto, pescoço, colo e mãos.Indicado para peles secas e maduras. Ideal para peles sensíveis, pois não causa alergias. ' , description_short: ' BioartMáscara de Argila Rosa 30mL ', sku: ' ESC2JWJE50 ' ,image1: File.open("#{Rails.root}/public/images/BioartMáscara de Argila Rosa 30mL.jpg"), image2: nil},
{name: ' BioartBlush 100% Mineral 4g ' , description: ' O blush mineral da linha Bioart Make-up é o primeiro blush ecológico do mundo com uma poderosa composição natural de argila e tapioca.Além de dar um toque especial na sua maquiagem, o blush mineral alimenta a derme do rosto, nutrindo-a com elementos minerais.Diferentemente de maquiagens comuns, não possui ingredientes prejudiciais à sua pele.Atua no aumento da elasticidade, deixando sua pele saudável, jovem e bonita.Equilibra a oleosidade e combate os poros abertos.Evita o envelhecimento extrínseco da derme, proporcionando uma barreira física de proteção aos raios UV e às fortes luzes artificiais. Excelente opção para proteção solar sem química. ' , description_short: ' BioartBlush 100% Mineral 4g ', sku: ' ESC2JWJE51 ' ,image1: File.open("#{Rails.root}/public/images/BioartBlush 100% Mineral 4g.jpg"), image2: nil},
{name: ' AlvaBatom 10g ' , description: ' Deixa seus lábios mais lindos, saudáveis, com cores maravilhosas e vibrantes.Tem longa duração e ajuda a manter a hidratação e nutrição dos lábios, proporcionando uma sensação de lábios de seda.Formulado com o Óleo de Rícino, Óleo de Semente de Damasco, Polissacarídeo, Vitamina E natural e Manteiga de Cacau. ' , description_short: ' AlvaBatom 10g ', sku: ' ESC2JWJE52 ' ,image1: File.open("#{Rails.root}/public/images/AlvaBatom 10g.jpg"), image2: nil},
{name: ' Surya Esmalte Exotic Animals 9,5mL ' , description: ' A linha de esmaltes Exotic Animals teve como inspiração as cores da natureza, para deixar suas unhas bonitas e saudáveis.Cores brilhantes e com tonalidades vibrantes, cada uma sendo dedicada a um animal exótico da fauna de diferentes lugares do mundo. ' , description_short: ' Surya Esmalte Exotic Animals 9,5mL ', sku: ' ESC2JWJE53 ' ,image1: File.open("#{Rails.root}/public/images/SuryaEsmalte Exotic Animals 9,5mL.jpg"), image2: nil},
{name: ' Kah-noaLeave-in Super Light Hidratante 300g ' , description: ' Especialmente para cabelos cacheados.Hidrata e deixa os cachos leves, macios e bem definidos.Penetra facilmente nos fios, respeitando o volume natural do cabelo cacheado. ' , description_short: ' Kah-noaLeave-in Super Light Hidratante 300g ', sku: ' ESC2JWJE54 ' ,image1: File.open("#{Rails.root}/public/images/Kah-noaLeave-in Super Light Hidratante 300g.jpg"), image2: nil},
{name: ' Surya Condicionador Murumuru Amazônia Preciosa 300mL ' , description: ' É indicado para cabelos oleosos.Condiciona e hidrata profundamente, regulando a oleosidade dos fios e mantendo o couro cabeludo saudável.O Murumuru é rico em provitaminas A e C e em Ômega 3,6 e 9, que regulam e limpam o excesso de óleo nos cabelos e hidratam as pontas secas, garantindo um visual balanceado ao cabelo. ' , description_short: ' Surya Condicionador Murumuru Amazônia Preciosa 300mL ', sku: ' ESC2JWJE55 ' ,image1: File.open("#{Rails.root}/public/images/SuryaCondicionador Murumuru Amazônia Preciosa 300mL.jpg"), image2: nil},
{name: ' KurKit Kur Condicionador Hidratante Sabonete Corporal Emulsão para Pele Ressecada e Shampoo Hidratante 30mL ' , description: ' Indicado para todos os tipos de cabelo.Possui em sua fórmula ativos biotecnológicos, orgânicos e naturais.Deixa os cabelos mais fáceis de desembaraçar e pentear, mais macios e menos frágeis.O agente condicionador possui características especiais de suavidade e condicionamento. ' , description_short: ' KurKit Kur Condicionador Hidratante Sabonete Corporal Emulsão para Pele Ressecada e Shampoo Hidratante 30mL ', sku: ' ESC2JWJE56 ' ,image1: File.open("#{Rails.root}/public/images/KurKit Kur Condicionador Hidratante Sabonete Corporal Emulsão para Pele Ressecada e Shampoo Hidratante 30mL.jpg"), image2: nil},
{name: ' Máscara de Cílios Grandiôse 10ml Lancôme ' , description: ' Grandiôse apresenta uma nova forma de aplicação de máscaras, mais fácil e mais confortável.Seu design inovador permite melhor controle da aplicação: Com a simples rotação do aplicador, é possível ter uma perfeita posição do pincel, que se alinha sozinho às extremidades dos cílios tornando-os mais volumosos e bem separados até mesmo em áreas que até agora eram inalcançáveis. ' , description_short: ' Máscara de Cílios Grandiôse 10ml Lancôme ', sku: ' ESC2JWJE57 ' ,image1: File.open("#{Rails.root}/public/images/Máscara de Cílios Grandiôse 10ml Lancôme.jpg"), image2: nil},
{name: ' Sombra 5 Couleurs Skyline - Skyline Collection Dior 806 Capital Of Light ' , description: ' Inspirada pela icônica arquitetura da Torre Eiffel, Dior revisita sua tradicional paleta 5 Couleurs com duas edições limitadas, matizes profundas, luminosidade e ricos contrastes.Tons acinzentados harmoniosamente exploram a pureza do azul e o frescor do bege, enquanto uma variedade de marrons quentes e luminosos se desenrola ao redor do rosa.Textura em véu ultra-pigmentado, que não deixa para trás nenhuma camada de pó.A paleta conta ainda com dois aplicadores de ponta dupla para uma variedade de finalizações. ' , description_short: ' Sombra 5 Couleurs Skyline - Skyline Collection Dior 806 Capital Of Light ', sku: ' ESC2JWJE58 ' ,image1: File.open("#{Rails.root}/public/images/Sombra 5 Couleurs Skyline - Skyline Collection Dior 806 Capital Of Light.jpg"), image2: nil},]

products.each_with_index do |p, i|
  product = Product.new(name: p[:name] , description: p[:description], description_short: p[:description_short], sku: "#{(0...8).map { sku[rand(sku.length)] }.join}", cost_price: 0.0, sale_price: (2*(3*i)+15).to_f, weight: 0.1, height: 16, width: 15, depth: 16, qty_max_in_cart: 10, active: true, featured: (i%2 == 0),
  promotional_price: (i%2 == 0) ? (2*(3+i)).to_f : 0.0)


  product.categories << Category.find(rand(1..categories.size))
  product.pictures << Gallery.create(media: p[:image1])
  product.pictures << Gallery.create(media: p[:image2]) unless p[:image2].nil?
  product.save
  puts product.sku
end


puts Access.create(id: 1, name: 'ADMIN')
puts Access.create(id: 2, name: 'MANAGER')
puts Access.create(id: 3, name: 'CUSTOMER')

puts Customer.create(name: 'Marcio', email: 'marcio@mail.com', password: '123456', access_id: 1, cpf: '012.345.678-90')
puts Customer.create(name: 'Eilane', email: 'eilane@mail.com', password: '123456', cpf: '012.345.678-90')
puts Customer.create(name: 'Igor', email: 'igor@mail.com', password: '123456', cpf: '012.345.678-90')
puts Customer.create(name: 'Diogo', email: 'diogo@mail.com', password: '123456', cpf: '012.345.678-90')
puts Customer.create(name: 'Mateus', email: 'mateus@mail.com', password: '123456', cpf: '012.345.678-90')

puts OrderStatus.create! id: 1, name: "Pendente"
puts OrderStatus.create! id: 2, name: "Aguardando Pagamento"
puts OrderStatus.create! id: 3, name: "Aguardando Entrega"
puts OrderStatus.create! id: 4, name: "Entregue"
puts OrderStatus.create! id: 5, name: "Fechado"
puts OrderStatus.create! id: 6, name: "Cancelado"

states = [{unit: 'AC', name: 'Acre'}, {name:'Alagoas', unit:'AL'},{name: 'Amapá', unit:'AP'},{name: 'Amazonas', unit: 'AM'},{name:'Bahia', unit:'BA'},{name:'Ceará', unit:'CE'},{name: 'Distrito Federal', unit:'DF'},{name:'Espírito Santo', unit: 'ES'},{name:'Goiás',unit:'GO'},{name:'Maranhão',unit:'MA'},{name:'Mato Grosso do Sul', unit:'MS'},{name:'Mato Grosso',unit:'MT'},{name:'Minas Gerais',unit:'MG'},{name:'Pará',unit:'PA'},{name:'Paraíba',unit:'PB'},{name:'Paraná',unit:'PR'},{name:'Pernambuco',unit:'PE'},{name:'Piauí',unit:'PI'},{name:'Rio de Janeiro',unit:'RJ'},{name:'Rio Grande do Norte',unit:'RN'},{name:'Rio Grande do Sul',unit:'RS'},{name:'Rondônia',unit:'RO'},{name:'Roraima',unit:'RR'},{name:'Santa Catarina',unit:'SC'},{name:'São Paulo',unit:'SP'},{name:'Sergipe',unit:'SE'},{name:'Tocantins',unit:'TO'}]

State.create(states)

address = Address.create(type_address: 'AVENIDA', street: 'Engenheiro Eusébio Stevaux', number: '823', postal_code: '04696-000', neighborhood: 'Santo Amaro', city: 'São Paulo', country: 'Brasil', alias: 'FACULDADE', state_id: 25)
Customer.all.each do |customer|
  customer.addresses << address  
end

total_customer = Customer.all.count

(1..200).each do |index|
  pay = Payment.create(name: (index % 2 == 0 ? 'pagSeguro' : 'creditCard'), active: true)
  customer = Customer.find(rand(1..total_customer))  
  shipping = (index % 2 == 0 ? 19.9 : 22.9)
  order = Order.create(order_number: 1000+index, payment: pay, customer: customer, order_status: (index % 2 == 0 ? OrderStatus.find(1) : OrderStatus.find(2)), address_id: address.id, shipping_name: (index % 2 == 0 ? 'PAC' : 'SEDEX'), shipping: shipping)
  (1..6).each do |index0|
    quantity = rand(1..4)
    product = Product.find(rand(1..products.size))
    total_price = product.sale_price * quantity
    OrderItem.create(product_id: product.id, order_id: order.id, unit_price: product.sale_price, quantity: quantity, total_price: total_price, created_at: Time.now - index.day, updated_at: Time.now - index.day)
  end
end
Order.all.each do |order|
  order.update({subtotal: order.sub_total, total: order.final_total})
end
puts " ==================== FINALIZOU O SEEDS EM #{Time.now} ======================"